import { Property } from '@/types'

export const properties: Property[] = [
  {
    slug: 'lakeshore-grand-retreat',
    name: 'Lakeshore Grand Retreat',
    tagline: 'Where the water meets luxury.',
    address: '2149 Lakeshore Drive',
    city: 'Fennville',
    state: 'MI',
    zipCode: '49408',
    bedrooms: 8,
    bathrooms: 8.5,
    maxGuests: 26,
    description:
      'Wake up to breathtaking lakeshore views from this stunning Michigan retreat. Designed for groups and families who refuse to compromise on comfort, Lakeshore Grand blends upscale finishes with an effortless indoor-outdoor lifestyle.',
    longDescription: `A luxury lakeshore retreat in Fennville, Michigan — designed for groups who want space, comfort, and water access.

Spacious 8 bed/8.5 bath luxury home just steps from Lake Michigan beach access and public parks.

Featuring a private theater room, game room, heated pool, hot tub, sauna and multiple living spaces.

Each bedroom has a private bath perfect for large groups, retreats, or family gatherings. Enjoy sunsets, beach days, and local wineries, all just minutes away from this well-appointed estate.`,
    highlights: [
      { icon: '\u{1F30A}', label: 'Lake Access' },
      { icon: '\u{1F3AC}', label: 'Theatre Room' },
      { icon: '♨️', label: 'Hot Tub' },
      { icon: '\u{1F9D6}', label: 'Sauna' },
      { icon: '\u{1F6CF}️', label: '8 Bedrooms' },
      { icon: '\u{1F465}', label: 'Sleeps 26' },
    ],
    amenities: [
      'Lake Access',
      'Heated Pool',
      'Hot Tub',
      'Sauna',
      'Theatre Room',
      'Game Room (Ping Pong & Foosball)',
      'Paddle Boards',
      "Chef's Kitchen",
      'Fire Pit',
      'Free High-Speed WiFi',
    ],
    images: [
      '/images/lakeshore/Front-Exterior-Dusk.jpg',
      '/images/lakeshore/Front-Exterior-Noon.jpg',
      '/images/lakeshore/LivingRoom1(1).jpg',
      '/images/lakeshore/LivingRoom1(2).jpg',
      '/images/lakeshore/Kitchen1(1).jpg',
      '/images/lakeshore/Kitchen1(2).jpg',
      '/images/lakeshore/DiningRoom1(1).jpg',
      '/images/lakeshore/DiningRoom1(2).jpg',
      '/images/lakeshore/OutdoorPatio.jpg',
      '/images/lakeshore/FrontEntrance1.jpg',
      '/images/lakeshore/Bedroom1.jpg',
      '/images/lakeshore/Bedroom1Bathroom1.jpg',
      '/images/lakeshore/Bedroom1Bathroom2.jpg',
      '/images/lakeshore/Bedroom2.jpg',
      '/images/lakeshore/Bedroom2Bathroom1(1).jpg',
      '/images/lakeshore/Bedroom2Bathroom1(2).jpg',
      '/images/lakeshore/Bedroom3.jpg',
      '/images/lakeshore/Bedroom3Bathroom1.jpg',
      '/images/lakeshore/Bedroom4.jpg',
      '/images/lakeshore/Bedroom4Bathroom1.jpg',
      '/images/lakeshore/KitchenPantry.jpg',
      '/images/lakeshore/Bathroom1.jpg',
      '/images/lakeshore/2ndFloorStairs.jpg',
      '/images/lakeshore/Mudroom.jpg',
      '/images/lakeshore/LaundryRoom.jpg',
    ],
    heroImage: '/images/lakeshore/Front-Exterior-Dusk.jpg',
    status: 'available',
    icalUrl: null,
    availableRanges: [
      ['2026-06-01', '2026-06-06'],
      ['2026-08-28', '2026-09-30'],
    ],
    featured: true,
  },
  {
    slug: 'blueberry-grand-retreat',
    name: 'Blueberry Grand Retreat',
    tagline: 'Modern luxury. Stunning amenities. Unforgettable.',
    address: '1816 Blueberry Lane',
    city: 'Fennville',
    state: 'MI',
    zipCode: '49408',
    bedrooms: 8,
    bathrooms: 8.5,
    maxGuests: 34,
    description:
      'A custom-built architectural masterpiece set on rolling Michigan hills. Blueberry Grand features a private pool, barrel sauna, pool house, and fire pit — everything you need for the perfect group escape.',
    longDescription: `A brand-new custom-built luxury home in Fennville, Michigan.

Sleeps 34 with 7 king beds and 22 twins—each bedroom has its own private bathroom. Enjoy a year-round heated pool, hot tub, sauna, theatre room, and a large yard with a pool house gaming room. Less than 5 minutes from Lake Michigan, surrounded by blueberry fields, and close to top wineries and cider houses.`,
    highlights: [
      { icon: '\u{1F3CA}', label: 'Private Pool' },
      { icon: '♨️', label: 'Hot Tub' },
      { icon: '\u{1F9D6}', label: 'Barrel Sauna' },
      { icon: '\u{1F3AE}', label: 'Game Room' },
      { icon: '\u{1F6CF}️', label: '8 Bedrooms' },
      { icon: '\u{1F465}', label: 'Sleeps 34' },
    ],
    amenities: [
      'Private Heated Pool',
      'Hot Tub',
      'Barrel Sauna',
      'Game Room (Air Hockey, Ping Pong & Foosball)',
      'Pool House & Covered Patio',
      'Fire Pit',
      'Free High-Speed WiFi',
    ],
    images: [
      '/images/blueberry/blueberry-01.jpg',
      '/images/blueberry/blueberry-02.jpg',
      '/images/blueberry/blueberry-03.jpg',
      '/images/blueberry/blueberry-04.jpg',
      '/images/blueberry/blueberry-05.jpg',
      '/images/blueberry/blueberry-06.jpg',
      '/images/blueberry/blueberry-07.jpg',
      '/images/blueberry/blueberry-08.jpg',
      '/images/blueberry/blueberry-09.jpg',
      '/images/blueberry/blueberry-10.jpg',
      '/images/blueberry/blueberry-11.jpg',
      '/images/blueberry/blueberry-12.jpg',
      '/images/blueberry/blueberry-13.jpg',
      '/images/blueberry/blueberry-14.jpg',
      '/images/blueberry/blueberry-15.jpg',
      '/images/blueberry/blueberry-16.jpg',
      '/images/blueberry/blueberry-17.jpg',
      '/images/blueberry/blueberry-18.jpg',
      '/images/blueberry/blueberry-19.jpg',
      '/images/blueberry/blueberry-20.jpg',
      '/images/blueberry/blueberry-21.jpg',
      '/images/blueberry/blueberry-22.jpg',
      '/images/blueberry/blueberry-23.jpg',
      '/images/blueberry/blueberry-24.jpg',
      '/images/blueberry/blueberry-25.jpg',
      '/images/blueberry/blueberry-26.jpg',
      '/images/blueberry/blueberry-27.jpg',
      '/images/blueberry/blueberry-28.jpg',
      '/images/blueberry/blueberry-29.jpg',
      '/images/blueberry/blueberry-30.jpg',
      '/images/blueberry/blueberry-31.jpg',
      '/images/blueberry/blueberry-32.jpg',
      '/images/blueberry/blueberry-33.jpg',
      '/images/blueberry/blueberry-34.jpg',
      '/images/blueberry/blueberry-35.jpg',
      '/images/blueberry/blueberry-36.jpg',
      '/images/blueberry/blueberry-37.jpg',
      '/images/blueberry/blueberry-38.jpg',
      '/images/blueberry/blueberry-39.jpg',
      '/images/blueberry/blueberry-40.jpg',
      '/images/blueberry/blueberry-41.jpg',
      '/images/blueberry/blueberry-42.jpg',
      '/images/blueberry/blueberry-43.jpg',
      '/images/blueberry/blueberry-44.jpg',
      '/images/blueberry/blueberry-45.jpg',
      '/images/blueberry/blueberry-49.jpg',
      '/images/blueberry/blueberry-51.jpg',
      '/images/blueberry/blueberry-52.jpg',
      '/images/blueberry/blueberry-53.jpg',
      '/images/blueberry/blueberry-54.jpg',
      '/images/blueberry/blueberry-55.jpg',
      '/images/blueberry/blueberry-56.jpg',
      '/images/blueberry/blueberry-57.jpg',
      '/images/blueberry/blueberry-58.jpg',
      '/images/blueberry/blueberry-59.jpg',
      '/images/blueberry/blueberry-60.jpg',
      '/images/blueberry/blueberry-61.jpg',
      '/images/blueberry/blueberry-62.jpg',
      '/images/blueberry/blueberry-63.jpg',
      '/images/blueberry/blueberry-64.jpg',
      '/images/blueberry/blueberry-65.jpg',
      '/images/blueberry/blueberry-66.jpg',
      '/images/blueberry/blueberry-67.jpg',
      '/images/blueberry/blueberry-68.jpg',
    ],
    heroImage: '/images/blueberry/blueberry-01.jpg',
    status: 'available',
    icalUrl: null,
    availableRanges: [
      ['2026-06-18', '2026-06-27'],
      ['2026-07-18', '2026-07-21'],
      ['2026-08-09', '2026-08-12'],
      ['2026-08-17', '2026-09-02'],
      ['2026-09-07', '2026-09-30'],
    ],
    featured: true,
  },
  {
    slug: 'clam-lake-grand-retreat',
    name: 'Clam Lake Grand Retreat',
    tagline: 'Serene up-north living on beautiful Clam Lake.',
    address: '8407 Clam Lake Road',
    city: 'Bellaire',
    state: 'MI',
    zipCode: '49615',
    bedrooms: 8,
    bathrooms: 8.5,
    maxGuests: 34,
    description:
      'Nestled on the shores of picturesque Clam Lake in Bellaire, this retreat offers a quintessential up-north Michigan experience — peaceful mornings, stunning water views, and starry nights around the fire.',
    longDescription: `Nestled along beautiful Clam Lake, this luxury 8-bedroom, 8.5-bath retreat was designed for unforgettable group getaways, family vacations, and lakeside relaxation. With spacious gathering areas, resort-style amenities, and direct access to the water, this property offers the perfect blend of comfort, entertainment, and privacy.

Spend your days enjoying the heated pool, soaking in the hot tub, unwinding in the sauna, or exploring the lake with the provided kayaks and paddle boards. The separate pool house features a full game room, creating the ultimate hangout space for kids and adults alike. In the evenings, gather around for movie nights in the private theater room or relax outdoors while taking in the peaceful lake atmosphere.

Inside, the home features eight spacious bedrooms and eight and a half bathrooms, giving large groups plenty of room to spread out comfortably. Whether you're cooking together, enjoying time by the pool, or heading out for a day on the water, the property is designed to comfortably accommodate memorable experiences for every guest.

Perfect for family reunions, retreats, weddings, and large group vacations, this one-of-a-kind Clam Lake escape combines upscale amenities with the beauty of Northern Michigan living.`,
    highlights: [
      { icon: '\u{1F3DE}', label: 'Clam Lake Access' },
      { icon: '\u{1F6A4}', label: 'Private Dock' },
      { icon: '\u{1F3CA}', label: 'Heated Pool' },
      { icon: '\u{1F6F6}', label: 'Kayaks and paddleboards Included' },
      { icon: '\u{1F6CF}️', label: '8 Bedrooms' },
      { icon: '\u{1F465}', label: 'Sleeps 34' },
    ],
    amenities: [
      'Clam Lake Access & Private Pier',
      'Heated Pool',
      'Hot Tub',
      'Sauna',
      'Kayaks Included',
      'Deck with Lake Views',
      'Fire Pit',
      'Free High-Speed WiFi',
    ],
    images: [],
    heroImage: '',
    status: 'available',
    icalUrl: null,
    availableRanges: null,
  },
]

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find(p => p.slug === slug)
}

export function getAllPropertySlugs(): string[] {
  return properties.map(p => p.slug)
}

export function getFeaturedProperties(): Property[] {
  return properties.filter(p => p.featured)
}
